eu_tickers = [
    "C.PA", # LVMH
    "ITX.MC", # Inditex
    "CDI.PA", # Dior
    "KER.PA", # Kering
    "RMS.PA", # Hermès
    "CFR.SW", # Richemont
    "ADS.DE", # adidas
    "9983.T", # Fast Retailing
    "LUX.MI", # Luxottica
    "HM-B.ST", # H&M
    "UHR.SW", # Swatch Group
    "ZAL.DE", # Zalando
    "1929.HK", # Chow Tai Fook
    "1913.HK", # Prada Group
    "BRBY.L", # Burberry
    "NXT.L", # Next
    "MONC.MI", # Moncler
    "ASC.L", # ASOS
    "LREN3.SA", # Lojas Renner
    "PUM.DE", # PUMA
    "MKS.L", # Marks & Spencer (M&S)
    "BOSS.DE", # Hugo Boss
    "GIL.TO", # Gildan
    "JD.L", # JD Sports
    "SFER.MI", # Salvatore Ferragamo
    "YNAP.MI", # YOOX Net-a-Porter Group
    "002563.SZ", # Semir
    "7936.T", # Asics
    "600612.SS", # Lao Feng Xiang Jewelry
    "BOO.L", # Boohoo.Com
    "SPD.L", # Sports Direct
    "GRND3.SA", # Grendene
    "TOD.MI", # TOD'S
    "ALPA4.SA", # Alpargatas - Havaianas
    "BC.MI", # Brunello Cucinelli
    "2331.HK", # Li Ning
    "SGP.L", # Supergroup
    "TED.L", # Ted Baker
    "ABFRL.NS", # Pantaloons
    "ARVIND.NS", # Arvind
    "8016.T", # Onward Holdings
    "HBC.TO", # Hudson's Bay
    "7606.T", # United Arrows
    "002269.SZ", # Metersbonwe
    "HGTX3.SA", # Cia Hering
    "3998.HK", # Bosideng
    "GEO.MI", # GEOX
    "0330.HK", # Esprit
    "MUL.L", # Mulberry
    "VAN.BR", # Van de Velde
    "GWI1.DE", # Gerry Weber
]

us_tickers = [
    "NKE", # Nike
    "TJX", # TJX
    "VFC", # VF
    "COH", # Coach
    "LULU", # Lululemon
    "KORS", # Michael Kors
    "M", # Macy's
    "RL", # Ralph Lauren
    "JWN", # Nordstrom
    "PUM.DE", # PUMA
    "SKX", # Skechers
    "CRI", # Carter's
    "COLM", # Columbia Sportswear
    "FL", # Foot locker
    "DECK", # Deckers Outdoor
    "WWW", # Wolverine
    "BOO.L", # Boohoo.Com
    "SPD.L", # Sports Direct
]

tickers = [
    "MC.PA", # LVMH
    "NKE", # Nike
    "ITX.MC", # Inditex
    "CDI.PA", # Dior
    "KER.PA", # Kering
    "RMS.PA", # Hermès
    "TJX", # TJX
    "CFR.SW", # Richemont
    "ADS.DE", # adidas
    "9983.T", # Fast Retailing
    "LUX.MI", # Luxottica
    "ROST", # Ross Stores
    "VFC", # VF
    "HM-B.ST", # H&M
    "UHR.SW", # Swatch Group
    "COH", # Coach
    "ZAL.DE", # Zalando
    "GPS", # Gap
    "LB", # L Brands
    "TIF", # Tiffany & Co.
    "1929.HK", # Chow Tai Fook
    "PVH", # PVH HQ
    "LULU", # Lululemon
    "1913.HK", # Prada Group
    "VIPS", # Vipshop Holdings
    "BRBY.L", # Burberry
    "NXT.L", # Next
    "KORS", # Michael Kors
    "M", # Macy's
    "MONC.MI", # Moncler
    "RL", # Ralph Lauren
    "JWN", # Nordstrom
    "ASC.L", # ASOS
    "LREN3.SA", # Lojas Renner
    "HBI", # Hanes
    "UA", # Under Armour
    "PUM.DE", # PUMA
    "MKS.L", # Marks & Spencer (M&S)
    "SKX", # Skechers
    "BOSS.DE", # Hugo Boss
    "GIL.TO", # Gildan
    "CRI", # Carter's
    "COLM", # Columbia Sportswear
    "JD.L", # JD Sports
    "FL", # Foot locker
    "SFER.MI", # Salvatore Ferragamo
    "YNAP.MI", # YOOX Net-a-Porter Group
    "002563.SZ", # Semir
    "URBN", # Urban Outfitters
    "AEO", # American Eagle Outfitters
    "DKS", # Dick's Sporting Goods
    "7936.T", # Asics
    "DECK", # Deckers Outdoor
    "600612.SS", # Lao Feng Xiang Jewelry
    "WWW", # Wolverine
    "BOO.L", # Boohoo.Com
    "SPD.L", # Sports Direct
    "SHOO", # Steve Madden
    "GRND3.SA", # Grendene
    "TOD.MI", # TOD'S
    "ALPA4.SA", # Alpargatas - Havaianas
    "PLCE", # Children's Place
    "DDS", # Dillard's
    "BC.MI", # Brunello Cucinelli
    "2331.HK", # Li Ning
    "SGP.L", # Supergroup
    "TED.L", # Ted Baker
    "GIII", # G-III Apparel Group
    "ABFRL.NS", # Pantaloons
    "DSW", # DSW
    "ARVIND.NS", # Arvind
    "8016.T", # Onward Holdings
    "ANF", # Abercrombie & Fitch
    "OXM", # Oxford Industries
    "HBC.TO", # Hudson's Bay
    "GES", # GUESS
    "7606.T", # United Arrows
    "CAL", # Caleres
    "CHS", # Chico's    "JCP", # J.C. Penney
    "002269.SZ", # Metersbonwe
    "HGTX3.SA", # Cia Hering
    "BKE", # Buckle
    "3998.HK", # Bosideng
    "GEO.MI", # GEOX
    "GCO", # Genesco
    "0330.HK", # Esprit
    "MUL.L", # Mulberry
    "FOSL", # Fossil
    "VAN.BR", # Van de Velde
    "EXPR", # Express
    "ASNA", # Ascena Retail Group
    "GWI1.DE", # Gerry Weber
    "VRA", # Vera Bradley
    "CATO", # Cato Fashion
    "FRAN" # Francesca's
]
